version: '3'
services:
  app:
    build: backend
    environment:
      - FLASK_APP=webapp.app
      - FF_ENV=${FF_ENV}
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend/webapp:/code/webapp

  web:
    build: vue
    depends_on:
      - app
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
      - FF_ENV=${FF_ENV}
      - NODE_ENV=${FF_ENV}

  db:
    image: mysql:5.7.29
    environment:
      MYSQL_DATABASE: FreeFitness
      MYSQL_USER: freefitnessflask
      MYSQL_PASSWORD: chris
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    expose:
      - 3306
    ports:
      - 1337:3306
    volumes:
      - ./.data/db:/var/lib/mysql