version: '3'
services:
  app:
    build: backend
    environment:
    - FLASK_APP=app.app
    ports:
    - "5000:5000"
  web:
    build: proxy
    ports:
     - "8080:80"
    environment:
     - NGINX_PORT=80
